version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    assignees:
      - "plaird"
      - "guw"
    commit-message:
      prefix: "Dependabot:"
    open-pull-requests-limit: 2
