// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intellij/common.proto

package com.google.devtools.intellij.aspect;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArtifactLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blaze.ArtifactLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string relative_path = 2;</code>
     * @return The relativePath.
     */
    java.lang.String getRelativePath();
    /**
     * <code>string relative_path = 2;</code>
     * @return The bytes for relativePath.
     */
    com.google.protobuf.ByteString
        getRelativePathBytes();

    /**
     * <code>bool is_source = 3;</code>
     * @return The isSource.
     */
    boolean getIsSource();

    /**
     * <pre>
     * path from the execution root to the actual root:
     * exec_root + root_execution_path_fragment + relative_path = absolute_path
     * </pre>
     *
     * <code>string root_execution_path_fragment = 4;</code>
     * @return The rootExecutionPathFragment.
     */
    java.lang.String getRootExecutionPathFragment();
    /**
     * <pre>
     * path from the execution root to the actual root:
     * exec_root + root_execution_path_fragment + relative_path = absolute_path
     * </pre>
     *
     * <code>string root_execution_path_fragment = 4;</code>
     * @return The bytes for rootExecutionPathFragment.
     */
    com.google.protobuf.ByteString
        getRootExecutionPathFragmentBytes();

    /**
     * <pre>
     * whether this artifact comes from an external repository (bazel only)
     * </pre>
     *
     * <code>bool is_external = 5;</code>
     * @return The isExternal.
     */
    boolean getIsExternal();
  }
  /**
   * Protobuf type {@code blaze.ArtifactLocation}
   */
  public static final class ArtifactLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:blaze.ArtifactLocation)
      ArtifactLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArtifactLocation.newBuilder() to construct.
    private ArtifactLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArtifactLocation() {
      relativePath_ = "";
      rootExecutionPathFragment_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ArtifactLocation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.intellij.aspect.Common.internal_static_blaze_ArtifactLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.intellij.aspect.Common.internal_static_blaze_ArtifactLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.intellij.aspect.Common.ArtifactLocation.class, com.google.devtools.intellij.aspect.Common.ArtifactLocation.Builder.class);
    }

    public static final int RELATIVE_PATH_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object relativePath_ = "";
    /**
     * <code>string relative_path = 2;</code>
     * @return The relativePath.
     */
    @java.lang.Override
    public java.lang.String getRelativePath() {
      java.lang.Object ref = relativePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relativePath_ = s;
        return s;
      }
    }
    /**
     * <code>string relative_path = 2;</code>
     * @return The bytes for relativePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRelativePathBytes() {
      java.lang.Object ref = relativePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relativePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_SOURCE_FIELD_NUMBER = 3;
    private boolean isSource_ = false;
    /**
     * <code>bool is_source = 3;</code>
     * @return The isSource.
     */
    @java.lang.Override
    public boolean getIsSource() {
      return isSource_;
    }

    public static final int ROOT_EXECUTION_PATH_FRAGMENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rootExecutionPathFragment_ = "";
    /**
     * <pre>
     * path from the execution root to the actual root:
     * exec_root + root_execution_path_fragment + relative_path = absolute_path
     * </pre>
     *
     * <code>string root_execution_path_fragment = 4;</code>
     * @return The rootExecutionPathFragment.
     */
    @java.lang.Override
    public java.lang.String getRootExecutionPathFragment() {
      java.lang.Object ref = rootExecutionPathFragment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rootExecutionPathFragment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * path from the execution root to the actual root:
     * exec_root + root_execution_path_fragment + relative_path = absolute_path
     * </pre>
     *
     * <code>string root_execution_path_fragment = 4;</code>
     * @return The bytes for rootExecutionPathFragment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRootExecutionPathFragmentBytes() {
      java.lang.Object ref = rootExecutionPathFragment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rootExecutionPathFragment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_EXTERNAL_FIELD_NUMBER = 5;
    private boolean isExternal_ = false;
    /**
     * <pre>
     * whether this artifact comes from an external repository (bazel only)
     * </pre>
     *
     * <code>bool is_external = 5;</code>
     * @return The isExternal.
     */
    @java.lang.Override
    public boolean getIsExternal() {
      return isExternal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relativePath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relativePath_);
      }
      if (isSource_ != false) {
        output.writeBool(3, isSource_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootExecutionPathFragment_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rootExecutionPathFragment_);
      }
      if (isExternal_ != false) {
        output.writeBool(5, isExternal_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relativePath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relativePath_);
      }
      if (isSource_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isSource_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootExecutionPathFragment_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rootExecutionPathFragment_);
      }
      if (isExternal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isExternal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.devtools.intellij.aspect.Common.ArtifactLocation)) {
        return super.equals(obj);
      }
      com.google.devtools.intellij.aspect.Common.ArtifactLocation other = (com.google.devtools.intellij.aspect.Common.ArtifactLocation) obj;

      if (!getRelativePath()
          .equals(other.getRelativePath())) return false;
      if (getIsSource()
          != other.getIsSource()) return false;
      if (!getRootExecutionPathFragment()
          .equals(other.getRootExecutionPathFragment())) return false;
      if (getIsExternal()
          != other.getIsExternal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RELATIVE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getRelativePath().hashCode();
      hash = (37 * hash) + IS_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSource());
      hash = (37 * hash) + ROOT_EXECUTION_PATH_FRAGMENT_FIELD_NUMBER;
      hash = (53 * hash) + getRootExecutionPathFragment().hashCode();
      hash = (37 * hash) + IS_EXTERNAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsExternal());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.devtools.intellij.aspect.Common.ArtifactLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blaze.ArtifactLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blaze.ArtifactLocation)
        com.google.devtools.intellij.aspect.Common.ArtifactLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.devtools.intellij.aspect.Common.internal_static_blaze_ArtifactLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.devtools.intellij.aspect.Common.internal_static_blaze_ArtifactLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.devtools.intellij.aspect.Common.ArtifactLocation.class, com.google.devtools.intellij.aspect.Common.ArtifactLocation.Builder.class);
      }

      // Construct using com.google.devtools.intellij.aspect.Common.ArtifactLocation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        relativePath_ = "";
        isSource_ = false;
        rootExecutionPathFragment_ = "";
        isExternal_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.devtools.intellij.aspect.Common.internal_static_blaze_ArtifactLocation_descriptor;
      }

      @java.lang.Override
      public com.google.devtools.intellij.aspect.Common.ArtifactLocation getDefaultInstanceForType() {
        return com.google.devtools.intellij.aspect.Common.ArtifactLocation.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.devtools.intellij.aspect.Common.ArtifactLocation build() {
        com.google.devtools.intellij.aspect.Common.ArtifactLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.devtools.intellij.aspect.Common.ArtifactLocation buildPartial() {
        com.google.devtools.intellij.aspect.Common.ArtifactLocation result = new com.google.devtools.intellij.aspect.Common.ArtifactLocation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.devtools.intellij.aspect.Common.ArtifactLocation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.relativePath_ = relativePath_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isSource_ = isSource_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rootExecutionPathFragment_ = rootExecutionPathFragment_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isExternal_ = isExternal_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.devtools.intellij.aspect.Common.ArtifactLocation) {
          return mergeFrom((com.google.devtools.intellij.aspect.Common.ArtifactLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.devtools.intellij.aspect.Common.ArtifactLocation other) {
        if (other == com.google.devtools.intellij.aspect.Common.ArtifactLocation.getDefaultInstance()) return this;
        if (!other.getRelativePath().isEmpty()) {
          relativePath_ = other.relativePath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getIsSource() != false) {
          setIsSource(other.getIsSource());
        }
        if (!other.getRootExecutionPathFragment().isEmpty()) {
          rootExecutionPathFragment_ = other.rootExecutionPathFragment_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getIsExternal() != false) {
          setIsExternal(other.getIsExternal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                relativePath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 24: {
                isSource_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 24
              case 34: {
                rootExecutionPathFragment_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 34
              case 40: {
                isExternal_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object relativePath_ = "";
      /**
       * <code>string relative_path = 2;</code>
       * @return The relativePath.
       */
      public java.lang.String getRelativePath() {
        java.lang.Object ref = relativePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          relativePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string relative_path = 2;</code>
       * @return The bytes for relativePath.
       */
      public com.google.protobuf.ByteString
          getRelativePathBytes() {
        java.lang.Object ref = relativePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relativePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string relative_path = 2;</code>
       * @param value The relativePath to set.
       * @return This builder for chaining.
       */
      public Builder setRelativePath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        relativePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string relative_path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelativePath() {
        relativePath_ = getDefaultInstance().getRelativePath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string relative_path = 2;</code>
       * @param value The bytes for relativePath to set.
       * @return This builder for chaining.
       */
      public Builder setRelativePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        relativePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean isSource_ ;
      /**
       * <code>bool is_source = 3;</code>
       * @return The isSource.
       */
      @java.lang.Override
      public boolean getIsSource() {
        return isSource_;
      }
      /**
       * <code>bool is_source = 3;</code>
       * @param value The isSource to set.
       * @return This builder for chaining.
       */
      public Builder setIsSource(boolean value) {
        
        isSource_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_source = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSource_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object rootExecutionPathFragment_ = "";
      /**
       * <pre>
       * path from the execution root to the actual root:
       * exec_root + root_execution_path_fragment + relative_path = absolute_path
       * </pre>
       *
       * <code>string root_execution_path_fragment = 4;</code>
       * @return The rootExecutionPathFragment.
       */
      public java.lang.String getRootExecutionPathFragment() {
        java.lang.Object ref = rootExecutionPathFragment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rootExecutionPathFragment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * path from the execution root to the actual root:
       * exec_root + root_execution_path_fragment + relative_path = absolute_path
       * </pre>
       *
       * <code>string root_execution_path_fragment = 4;</code>
       * @return The bytes for rootExecutionPathFragment.
       */
      public com.google.protobuf.ByteString
          getRootExecutionPathFragmentBytes() {
        java.lang.Object ref = rootExecutionPathFragment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rootExecutionPathFragment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * path from the execution root to the actual root:
       * exec_root + root_execution_path_fragment + relative_path = absolute_path
       * </pre>
       *
       * <code>string root_execution_path_fragment = 4;</code>
       * @param value The rootExecutionPathFragment to set.
       * @return This builder for chaining.
       */
      public Builder setRootExecutionPathFragment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rootExecutionPathFragment_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path from the execution root to the actual root:
       * exec_root + root_execution_path_fragment + relative_path = absolute_path
       * </pre>
       *
       * <code>string root_execution_path_fragment = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRootExecutionPathFragment() {
        rootExecutionPathFragment_ = getDefaultInstance().getRootExecutionPathFragment();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path from the execution root to the actual root:
       * exec_root + root_execution_path_fragment + relative_path = absolute_path
       * </pre>
       *
       * <code>string root_execution_path_fragment = 4;</code>
       * @param value The bytes for rootExecutionPathFragment to set.
       * @return This builder for chaining.
       */
      public Builder setRootExecutionPathFragmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rootExecutionPathFragment_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private boolean isExternal_ ;
      /**
       * <pre>
       * whether this artifact comes from an external repository (bazel only)
       * </pre>
       *
       * <code>bool is_external = 5;</code>
       * @return The isExternal.
       */
      @java.lang.Override
      public boolean getIsExternal() {
        return isExternal_;
      }
      /**
       * <pre>
       * whether this artifact comes from an external repository (bazel only)
       * </pre>
       *
       * <code>bool is_external = 5;</code>
       * @param value The isExternal to set.
       * @return This builder for chaining.
       */
      public Builder setIsExternal(boolean value) {
        
        isExternal_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * whether this artifact comes from an external repository (bazel only)
       * </pre>
       *
       * <code>bool is_external = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsExternal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isExternal_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:blaze.ArtifactLocation)
    }

    // @@protoc_insertion_point(class_scope:blaze.ArtifactLocation)
    private static final com.google.devtools.intellij.aspect.Common.ArtifactLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.devtools.intellij.aspect.Common.ArtifactLocation();
    }

    public static com.google.devtools.intellij.aspect.Common.ArtifactLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArtifactLocation>
        PARSER = new com.google.protobuf.AbstractParser<ArtifactLocation>() {
      @java.lang.Override
      public ArtifactLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ArtifactLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArtifactLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.devtools.intellij.aspect.Common.ArtifactLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blaze_ArtifactLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blaze_ArtifactLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025intellij/common.proto\022\005blaze\"w\n\020Artifa" +
      "ctLocation\022\025\n\rrelative_path\030\002 \001(\t\022\021\n\tis_" +
      "source\030\003 \001(\010\022$\n\034root_execution_path_frag" +
      "ment\030\004 \001(\t\022\023\n\013is_external\030\005 \001(\010B%\n#com.g" +
      "oogle.devtools.intellij.aspectb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_blaze_ArtifactLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blaze_ArtifactLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blaze_ArtifactLocation_descriptor,
        new java.lang.String[] { "RelativePath", "IsSource", "RootExecutionPathFragment", "IsExternal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
