package(default_visibility = ["//visibility:public"])


# Tools

# This tool
py_binary(
    name = "eclipse_feature_xml_builder",
    srcs = ["eclipse_feature_xml_builder.py"],
    deps = ["//tools/gflags:gflags_lib"],
)
