package com.salesforce.bazel.sdk.aspect.jvm;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import com.salesforce.bazel.sdk.aspect.AspectTargetInfo;

/**
 * The subclass of AspectTargetInfo for JVM based rules.
 * <p>
 * The JSON document format is like this for a java_library rule:
 *
 * <pre>
 {
   "build_file_artifact_location":"helloworld/BUILD",
   "dependencies":["//proto:helloworld_java_proto"],
   "generated_jars":[],
   "jars":[
     {"interface_jar":"bazel-out/darwin-fastbuild/bin/helloworld/libhelloworld-hjar.jar",
      "jar":"bazel-out/darwin-fastbuild/bin/helloworld/libhelloworld.jar",
      "source_jar":"bazel-out/darwin-fastbuild/bin/helloworld/libhelloworld-src.jar"
     }
    ],
    "kind":"java_library",
    "label":"//helloworld:helloworld",
    "sources":["helloworld/src/main/java/helloworld/HelloWorld.java"]
 }
 * </pre>
 */
public class JVMAspectTargetInfo extends AspectTargetInfo {
    protected String mainClass;
    protected List<JVMAspectOutputJarSet> generatedJars;
    protected List<JVMAspectOutputJarSet> jars;

    JVMAspectTargetInfo(File aspectDataFile, JSONObject jsonObject, JSONParser jsonParser, String workspaceRelativePath, 
        String kind, String label, List<String> deps, List<String> sources) throws Exception {
        super(aspectDataFile, workspaceRelativePath, kind, label, deps, sources);
        
        List<JVMAspectOutputJarSet> jarsList = jsonArrayToJarArray(jsonObject.get("jars"), jsonParser);
        this.jars = jarsList;

        List<JVMAspectOutputJarSet> generatedJarsList = jsonArrayToJarArray(jsonObject.get("generated_jars"), jsonParser);
        this.generatedJars = generatedJarsList;
        
        String mainClass = (String) jsonObject.get("main_class");
        this.mainClass = mainClass;
    }
    
    /**
     * List of jars generated by annotations processors when building this target.
     */
    public List<JVMAspectOutputJarSet> getGeneratedJars() {
        return generatedJars;
    }

    /**
     * List of jars generated by building this target.
     */
    public List<JVMAspectOutputJarSet> getJars() {
        return jars;
    }

    /**
     * The value of the "main_class" attribute of this target, may be null if this target doesn't specify a main_class.
     */
    public String getMainClass() {
        return mainClass;
    }

    private static List<JVMAspectOutputJarSet> jsonArrayToJarArray(Object arrayObject, JSONParser jsonParser)
            throws Exception {
        List<JVMAspectOutputJarSet> jarList = new ArrayList<>();
        if (arrayObject == null) {
            return jarList;
        }
        if (!(arrayObject instanceof JSONArray)) {
            return jarList;
        }

        JSONArray array = (JSONArray) arrayObject;
        for (Object jarSet : array) {
            JSONObject jarSetObject = (JSONObject) jsonParser.parse(jarSet.toString());
            jarList.add(new JVMAspectOutputJarSet(jarSetObject));
        }
        return jarList;
    }



    @Override
    public String toString() {
        StringBuffer builder = new StringBuffer();
        builder.append("AspectTargetInfo(\n");
        builder.append("  label = ").append(label).append(",\n");
        builder.append("  build_file_artifact_location = ").append(workspaceRelativePath).append(",\n");
        builder.append("  kind = ").append(kind).append(",\n");
        builder.append("  jars = [").append(commaJoiner(jars)).append("],\n");
        builder.append("  generated_jars = [").append(commaJoiner(generatedJars)).append("],\n");
        builder.append("  dependencies = [").append(commaJoiner(deps)).append("],\n");
        builder.append("  sources = [").append(commaJoiner(sources)).append("]),\n");
        builder.append("  main_class = ").append(mainClass).append("),\n");
        return builder.toString();
    }

}
