java_import(
    name = "org_hamcrest_core",
    jars = [
        "lib/hamcrest-core-1.3.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)

java_import(
    name = "org_junit_junit",
    jars = [
        "lib/junit-4.12.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)

java_import(
    name = "org_mockito_mockito_core",
    jars = [
        "lib/mockito-core-2.28.2.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)

java_import(
    name = "net_bytebuddy_byte_buddy",
    jars = [
        "lib/byte-buddy-1.9.12.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)

java_import(
    name = "org_objenesis_objenesis",
    jars = [
        "lib/objenesis-2.6.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)

java_import(
    name = "com_google_truth",
    jars = [
        "lib/truth-0.31.jar",
    ],
    visibility = [
        "//visibility:public",
    ],
)
