#sh_binary(
#    name = "unzip-updatesite",
#    srcs = ["unzip-updatesite.sh"],
#    data = ["//feature:bazeleclipsefeature.zip"],
#)

py_binary(
    name = "site_builder",
    srcs = ["site_builder.py"],
    deps = ["//tools/gflags:gflags_lib"],
)
