name: Bazel Eclipse Feature Release

on:
  # manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          format: "YYYYMMDD_HHmm"

      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Import IntelliJ Aspects
        working-directory: ./bundles/com.salesforce.bazel.sdk/aspects/import
        run: ./import-and-build.sh

      - name: Build and Test
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        run: ./mvnw --batch-mode clean verify

      - name: Create the update-site layout on the filesystem
        id: create_layout
        shell: bash
        run: .github/bef-create-update-site.sh

      - name: Deploy Update Site 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: bef-staging
          clean: false
          commit-message: "Release Build ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
          ssh-key: ${{ secrets.DEPLOY_KEY }}
