name: Bazel Eclipse Feature CI

on:
  # manually from the Actions tab
  workflow_dispatch:
    inputs:
      buildId:
        description: 'Build Identifier (eg., "1.0", "1.0 RC1", "20201002-1227", etc.)'
        required: true
        default: 'Mona the Octocat'

jobs:
  build-and-deploy:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
  
      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD_HHmm'
        
      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
         
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build Everything
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        run: mvn --batch-mode --update-snapshots clean verify
        
      - name: Deploy Update Site 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: site
          single-commit: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}

    