name: Publish Test Results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      
permissions: {}

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: (test-results.*|ci-event-file)
          name_is_regexp: true
          path: artifacts
  
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/ci-event-file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
